The Simpelst Windows App: outputbuf< Elem > Class Template Reference
outputbuf< Elem > Class Template Reference
#include <output.hpp>
Public Member Functions
outputbuf ()
~outputbuf ()
Protected Member Functions
virtual int_type overflow (int_type c)
Private Types
typedef std::basic_streambuf< Elem >::int_type int_type
Private Member Functions
void flushMsg ()
outputbuf (outputbuf const &)
void operator= (outputbuf const &)
Private Attributes
std::basic_string< Elem > msg
buffer for current log message
Detailed Description
template<typename Elem>
class outputbuf< Elem >
Definition at line 66 of file output.hpp.
Member Typedef Documentation
int_type
template<typename Elem > typedef std::basic_streambuf<Elem>::int_type outputbuf< Elem >::int_type private
Definition at line 69 of file output.hpp.
Constructor & Destructor Documentation
outputbuf() [1/2]
template<typename Elem > outputbuf< Elem >::outputbuf () inline
Definition at line 82 of file output.hpp.
 { };
~outputbuf()
template<typename Elem > outputbuf< Elem >::~outputbuf () inline
Definition at line 83 of file output.hpp.
 { flushMsg(); }
References outputbuf< Elem >::flushMsg().
outputbuf() [2/2]
template<typename Elem > outputbuf< Elem >::outputbuf (outputbuf< Elem > const &) private
Member Function Documentation
flushMsg()
template<typename Elem > void outputbuf< Elem >::flushMsg () inline private
Definition at line 72 of file output.hpp.
     {
         if (msg.length() > 0)
         {
             flush(msg);
             msg.erase();    // erase message buffer
         }
     }
References flush(), and outputbuf< Elem >::msg.
Referenced by outputbuf< Elem >::overflow(), and outputbuf< Elem >::~outputbuf().
operator=()
template<typename Elem > void outputbuf< Elem >::operator= (outputbuf< Elem > const &) private
overflow()
template<typename Elem > virtual int_type outputbuf< Elem >::overflow (int_type c) inline protected virtual
Definition at line 86 of file output.hpp.
     {
         std::basic_ostream<Elem> tmp(this);
         if (c == tmp.widen('\n'))
         {
             flushMsg();
         }
         else
         {
             msg += c;
         }
         return c == -1 ? -1 : ' ';
     }
References outputbuf< Elem >::flushMsg(), and outputbuf< Elem >::msg.
Member Data Documentation
msg
template<typename Elem > std::basic_string<Elem> outputbuf< Elem >::msg private
buffer for current log message
Definition at line 70 of file output.hpp.
Referenced by outputbuf< Elem >::flushMsg(), and outputbuf< Elem >::overflow().
The documentation for this class was generated from the following file:
src/output.hpp