The Simpelst Windows App: Thread Class Reference
Thread Class Reference
This class represents a thread in the system.
#include <Thread.h>
Classes
struct Impl
The real implementation of Thread.
struct ThreadManager
Public Member Functions
virtual ~Thread ()
Destroy the Thread:: Thread object.
Code injection
start and enqueue are very similar in application
here you can specify any callable object (function, method, std::function, etc.) with all arguments, which will then be executed in the thread. While start which uses the callable object as the start function of the thread, enqueue enqueues the callable object in the thread's waiting queue and an event is fired, which requests the thread to process its queue.
Let's look at a simple startup example:
ThreadPtr thread1 = Thread::Manager["Thread1"];
if(!thread1->IsRunning)
    thread1->start([thread1]() {
   DoTheJob();
});
thread1->join();  // wait to the end of DoTheJob
And then the example of a reusable thread:
ThreadPtr thread1 = Thread::Manager["Thread1"];
if(!thread1->IsRunning)
    thread1->start();
for(size_t i = 0; i < 3; ++i)
 {
   thread1->enqueue([thread1]() {
       DoTheJob();
   });
 }
Template Parameters
_Fn the type callable.object
_Args the types of the parameters
Parameters
_Fx any callable object
_Ax arguments for the callable object
template<class _Fn , class... _Args>
void start (_Fn &&_Fx, _Args &&... _Ax)
The code that will be executed, after the new Thread is started.
template<class _Fn , class... _Args>
void enqueue (_Fn &&_Fx, _Args &&... _Ax)
The code that will be enqued in the threads task queue.
Thread control
Methods to control the flow of a thread
Start and enqueue
ThreadPtr thread1 = Thread::Manager["Thread1"];
if(!thread1->IsRunning)
    thread1->start();
for(size_t i = 0; i < 3; ++i)
 {
   thread1->enqueue([thread1]() {
       DoTheJob();
   });
 }
Stop and join
thread2->start([thread2]() {
    while(!thread2->IsStopped) // <--- here we checks every loop the IsStopped Property
    {
        Thread::sleep(300);
        mainThread->enqueues([thread2]() {
            static int count = 0;
            string progress[] = {"|","/", "-", "\\" };
            int size = sizeof(progress) / sizeof(string);
            ButtonPtr button = Button::Manager["Start:Button"];
            button->Caption = "Running " + progress[count % size];
            count++;
        });
    }
    // If the thread was stopped, we reset the text
    mainThread->enqueues([](){
         ButtonPtr button = Button::Manager["Start:Button"];
         button->Caption = "Start ...";
    });
});
 ...
void OnStartClicked(Button *button)
{
   ThreadPtr thread2 = Thread::Manager.find("Thread2");
   if(thread2)
   {
       thread2->stop();
       thread2->join();
   }
}
void start ()
Starts the Thread with Thread::Impl::standardLoop.
void stop ()
Method to stop the Trhead.
bool joinable ()
Reports whether the thread can be merged or not.
void join ()
Führt den Thread mit dem aktuellen zusammen.
Inclusion of existing threads
Methods to include already running threads
Globally, the following elements are necessary:
ThreadPtr mainThread;           //> The main thread instance
#define WM_THREAD WM_USER + 1   //> The Windows Message to communicate with the main thread
In the WinMain you have to do
ThreadPtr mainThread = Thread::Manager["MainThread"];
mainThread->initRunningThread(this_thread::get_id(), [hWnd]() {
     ::PostMessage(hWnd, WM_THREAD, (WPARAM)0, (LPARAM)0);
     });
And the WinProc Function must be extended like this:
case WM_THREAD:
    mainThread->processQueue();
    break;
void initRunningThread (ThreadId id, function< void()> notify)
Initializes a thread object with an already running thread.
void processQueue (size_t maxElements=10)
Processes maxElements in the running thread.
Static Public Member Functions
static void sleep (size_t milliseconds)
blocks the current thread for at least the given milliseconds
Public Attributes
PropertyR< bool > IsRunning
PropertyR< bool > IsStopped
PropertyR< ThreadId > Id
PropertyR< string > Name
Static Public Attributes
static struct Thread::ThreadManager Manager
Private Member Functions
Thread (const string &name)
Construct a new Thread:: Thread object.
void enqueue_ (function< void()> f)
push the functor in the queue
void start_ (thread &&t)
Private Attributes
unique_ptr< Impl > pImpl_
Detailed Description
This class represents a thread in the system.
A thread can be created and started again, it can be but also existing, running threads can be assigned.
For newly created threads, the start function can be included, or the Standard function can be used. The default function Thread::Impl::standardLoop supports the continuous exchange of function objects via a queue.
For own start functions or otherwise started threads, like the main thread the processing of the queue must be triggered from outside, via Thread::processQueue. You can also specify a notification callback to be called, if new function objects have been added to the queue.
All active threads are accessible through the Thread::Manager via a name or the ThreadId
Using for a background thread is very intuitive:
ThreadPtr thread1 = Thread::Manager["Thread1"];
if(!thread1->IsRunning)
    thread1->start();
for(size_t i = 0; i < 3; ++i)
 {
   thread1->enqueue([thread1]() {
       DoTheJob();
   });
 }
Thread1 remains in this case after the job has been completed Stand by and wait for the next job.
If only a specific task is to be completed, this can also be done this way:
ThreadPtr thread1 = Thread::Manager["Thread1"];
if(!thread1->IsRunning)
    thread1->start([thread1]() {
   DoTheJob();
});
thread1->join();  // wait to the end of DoTheJob
Thread1 ends in this case with DoTheJob() and will be removed from Manager, if no other ThreadPtr exists in the system
Another case is assigning the main thread of an application to a thread object:
Globally, the following elements are necessary:
ThreadPtr mainThread;           //> The main thread instance
#define WM_THREAD WM_USER + 1   //> The Windows Message to communicate with the main thread
In the WinMain you have to do
ThreadPtr mainThread = Thread::Manager["MainThread"];
mainThread->initRunningThread(this_thread::get_id(), [hWnd]() {
     ::PostMessage(hWnd, WM_THREAD, (WPARAM)0, (LPARAM)0);
     });
And the WinProc Function must be extended like this:
case WM_THREAD:
    mainThread->processQueue();
    break;
Definition at line 27 of file Thread.h.
Constructor & Destructor Documentation
Thread()
Thread::Thread (const string & name) explicit private
Construct a new Thread:: Thread object.
Parameters
name
Definition at line 479 of file Thread.cpp.
     : pImpl_(make_unique<Thread::Impl>(name))
     , Name(pImpl_->name_)
     , IsRunning([this]() {
           return pImpl_->id_ != ThreadId() && !IsStopped;
       })
     , IsStopped([this]() {
           return pImpl_->stopped_.load();
       })
     , Id([this]() {
           return pImpl_->id_;
       })
 {
 }
References IsStopped, and pImpl_.
~Thread()
Thread::~Thread () virtual
Destroy the Thread:: Thread object.
Definition at line 497 of file Thread.cpp.
 {
     if (pImpl_->thread_.joinable())
     {
         if(this_thread::get_id() == pImpl_->thread_.get_id())
         {
             pImpl_->thread_.detach();
         }
         else
         {
             pImpl_->stopped_ = true;
             pImpl_->thread_.join();
         }
     }
     // It is possible that global variables are deleted,
     // after the manager has already been cleared.
     // Hence this check here
     if (!Thread::ThreadManager::Impl::isDeleted)
     {
         lock_guard<recursive_mutex> lock(Thread::Manager.pImpl_->mutex_);
         Thread::Manager.pImpl_->nameMap_.erase(pImpl_->name_);
         Thread::Manager.pImpl_->idMap_.erase(pImpl_->id_);
     }
 }
References Thread::ThreadManager::Impl::isDeleted, Manager, Thread::ThreadManager::pImpl_, and pImpl_.
Member Function Documentation
enqueue()
template<class _Fn , class... _Args> void Thread::enqueue (_Fn && _Fx, _Args &&... _Ax) inline
The code that will be enqued in the threads task queue.
Threads which are started with the Thread::Impl::standardLoop, can thus accept new tasks. The tasks are added to the queue and processed as fast as possible
Definition at line 58 of file Thread.h.
     {
         auto f = bind(_Fx, std::forward<_Args>(_Ax)...);
         enqueue_(f);
     }
References enqueue_().
Referenced by Edit::add(), OnStartClicked(), and OnThreadTestClicked().
enqueue_()
void Thread::enqueue_ (function< void()> f) private
push the functor in the queue
Parameters
f functor to push in queue
Definition at line 595 of file Thread.cpp.
 {
     pImpl_->enqueue(f);
 }
References pImpl_.
Referenced by enqueue().
initRunningThread()
void Thread::initRunningThread (ThreadId id, function< void()> notify)
Initializes a thread object with an already running thread.
The notification function is called when the thread gets new items pushed to its queue
Parameters
id
notify
Definition at line 529 of file Thread.cpp.
 {
     pImpl_->initRunningThread(id, notify, shared_from_this());
 }
References pImpl_.
Referenced by WinMain().
join()
void Thread::join ()
Führt den Thread mit dem aktuellen zusammen.
Waits for the end of the thread.
The current thread waits until the requested thread is finished
Definition at line 626 of file Thread.cpp.
 {
     pImpl_->thread_.join();
 }
References pImpl_.
Referenced by Thread::ThreadManager::Impl::~Impl().
joinable()
bool Thread::joinable ()
Reports whether the thread can be merged or not.
Checks if the std::thread object identifies an active thread of execution. Specifically, returns true if get_id() != std::thread::id(). So a default constructed thread is not joinable. A thread that has finished executing code, but has not yet been joined is still considered an active thread of execution and is therefore joinable.
Returns
true if the thread object identifies an active thread of execution, false otherwise
Definition at line 617 of file Thread.cpp.
 {
     return pImpl_->thread_.joinable();
 }
References pImpl_.
Referenced by Thread::ThreadManager::Impl::~Impl().
processQueue()
void Thread::processQueue (size_t maxElements = 10)
Processes maxElements in the running thread.
Processes a maximum of the specified number of function objects in the queue.
After notification, all tasks are processed in this way.
Parameters
maxElements
Definition at line 605 of file Thread.cpp.
 {
     unique_lock<recursive_mutex> lock(pImpl_->mutex_);
     pImpl_->processQueue(lock, maxElements);
 }
References pImpl_.
Referenced by WndProc().
sleep()
void Thread::sleep (size_t milliseconds) static
blocks the current thread for at least the given milliseconds
Parameters
milliseconds
Definition at line 584 of file Thread.cpp.
 {
     std::this_thread::sleep_for(std::chrono::milliseconds(milliseconds));
     // throw exception(__FUNCTION__" not implemented");
 }
start() [1/2]
void Thread::start ()
Starts the Thread with Thread::Impl::standardLoop.
The most normal way to start a new thread.
After startup it is possible to push tasks to the thread queue
ThreadPtr thread1 = Thread::Manager["Thread1"];
if(!thread1->IsRunning)
    thread1->start();
for(size_t i = 0; i < 3; ++i)
 {
   thread1->enqueue([thread1]() {
       DoTheJob();
   });
 }
Definition at line 559 of file Thread.cpp.
 {
     ThreadPtr thisThread = shared_from_this();
     unique_lock<recursive_mutex> lock(pImpl_->mutex_);
     start_(thread(Impl::standardLoop, thisThread));
     pImpl_->condition_.wait(lock);
 }
References pImpl_, Thread::Impl::standardLoop(), and start_().
start() [2/2]
template<class _Fn , class... _Args> void Thread::start (_Fn && _Fx, _Args &&... _Ax) inline
The code that will be executed, after the new Thread is started.
This is the main functionallity of the Thread. Usually such a working thread is which should complete a task exactly once and then ends. If the task should be able to be aborted, it is important to check for IsStopped between all steps.
ThreadPtr thread1 = Thread::Manager["Thread1"];
if(!thread1->IsRunning)
    thread1->start([thread1]() {
   DoTheJob();
});
thread1->join();  // wait to the end of DoTheJob
Definition at line 49 of file Thread.h.
     {
         ThreadPtr thisThread = shared_from_this();
         start_(thread([thisThread, _Fn](typename std::forward<_Args>(_Ax)...){
             _Fn(std::forward<_Args>(_Ax)...);
         }));
     }
References start_().
Referenced by OnStartClicked().
start_()
void Thread::start_ (thread && t) private
Parameters
t
Definition at line 539 of file Thread.cpp.
 {
     if (pImpl_->thread_.joinable())
     {
         pImpl_->stopped_ = true;
         pImpl_->thread_.join();
         //pImpl_->thread_.detach();
     }
     swap(pImpl_->thread_, t);
     pImpl_->stopped_ = false;
     pImpl_->id_ = pImpl_->thread_.get_id();
     lock_guard<recursive_mutex> lock(Thread::Manager.pImpl_->mutex_);
     Thread::Manager.pImpl_->idMap_.insert(make_pair(pImpl_->id_, shared_from_this()));
 }
References Manager, Thread::ThreadManager::pImpl_, and pImpl_.
Referenced by start().
stop()
void Thread::stop ()
Method to stop the Trhead.
Internally, the IsStopped property is set. When the executing thread detects that this property is True, it should finish or abort its work as soon as possible
thread2->start([thread2]() {
    while(!thread2->IsStopped) // <--- here we checks every loop the IsStopped Property
    {
        Thread::sleep(300);
        mainThread->enqueues([thread2]() {
            static int count = 0;
            string progress[] = {"|","/", "-", "\\" };
            int size = sizeof(progress) / sizeof(string);
            ButtonPtr button = Button::Manager["Start:Button"];
            button->Caption = "Running " + progress[count % size];
            count++;
        });
    }
    // If the thread was stopped, we reset the text
    mainThread->enqueues([](){
         ButtonPtr button = Button::Manager["Start:Button"];
         button->Caption = "Start ...";
    });
});
 ...
void OnStartClicked(Button *button)
{
   ThreadPtr thread2 = Thread::Manager.find("Thread2");
   if(thread2)
   {
       thread2->stop();
       thread2->join();
   }
}
Definition at line 567 of file Thread.cpp.
 {
     pImpl_->stopped_ = true;
     pImpl_->condition_.notify_one();
     this_thread::yield();
     {
         lock_guard<recursive_mutex> lock(Thread::Manager.pImpl_->mutex_);
         Thread::Manager.pImpl_->idMap_.erase(pImpl_->id_);
     }
     pImpl_->id_ = ThreadId();
 }
References Manager, Thread::ThreadManager::pImpl_, and pImpl_.
Referenced by OnStartClicked(), and Thread::ThreadManager::Impl::~Impl().
Member Data Documentation
Id
PropertyR<ThreadId> Thread::Id
Definition at line 84 of file Thread.h.
Referenced by Edit::add().
IsRunning
PropertyR<bool> Thread::IsRunning
Definition at line 82 of file Thread.h.
Referenced by OnStartClicked().
IsStopped
PropertyR<bool> Thread::IsStopped
Definition at line 83 of file Thread.h.
Referenced by OnStartClicked(), and Thread().
Manager
Thread::ThreadManager Thread::Manager static
Definition at line 472 of file Thread.cpp.
Referenced by Thread::Impl::initRunningThread(), OnStartClicked(), OnThreadTestClicked(), Thread::Impl::standardLoop(), start_(), stop(), WinMain(), and ~Thread().
Name
PropertyR<string> Thread::Name
Definition at line 85 of file Thread.h.
Referenced by Thread::Impl::standardLoop().
pImpl_
unique_ptr<Impl> Thread::pImpl_ private
Definition at line 77 of file Thread.h.
Referenced by Thread::ThreadManager::currentThread(), enqueue_(), Thread::ThreadManager::find(), initRunningThread(), Thread::Impl::initRunningThread(), join(), joinable(), Thread::ThreadManager::operator[](), processQueue(), Thread::Impl::standardLoop(), start(), start_(), stop(), Thread(), and ~Thread().
The documentation for this class was generated from the following files:
src/Base/Thread.h
src/Base/Thread.cpp