The Simpelst Windows App: TestCase Class Reference
TestCase Class Reference abstract
#include <TestCase.h>
Public Member Functions
virtual ~TestCase ()=default
virtual void buildUp ()
virtual TestResult runTest ()=0
virtual void breakDown ()
Static Public Member Functions
static bool addTestCase (const string &name, TestCasePtr testCase)
static void writeOutput (const VectorOfStringVectors &outputs)
static TestResult runTests (const string &testPattern="*")
Detailed Description
Definition at line 20 of file TestCase.h.
Constructor & Destructor Documentation
~TestCase()
virtual TestCase::~TestCase () virtual default
Member Function Documentation
addTestCase()
bool TestCase::addTestCase (const string & name, TestCasePtr testCase) static
Definition at line 54 of file TestCase.cpp.
 {
     CaseMap& testCases = getCases();
     return !testCases.insert(make_pair(name, testCase)).second;
 }
References anonymous_namespace{TestCase.cpp}::getCases().
breakDown()
virtual void TestCase::breakDown () inline virtual
Definition at line 26 of file TestCase.h.
 {}
buildUp()
virtual void TestCase::buildUp () inline virtual
Definition at line 24 of file TestCase.h.
 {}
runTest()
virtual TestResult TestCase::runTest () pure virtual
Implemented in ValueTests, PropertyTests, and BaseTests.
runTests()
TestResult TestCase::runTests (const string & testPattern = "*") static
Definition at line 60 of file TestCase.cpp.
 {
     stringVector labels = { "Test name","Buildup (ms)","Test result","Test (ms)","Breakdown (ms)", "Total (ms)" };
     VectorOfstringVectors outputs = { labels };
     NameChecker check(testPattern);
     CaseMap& testCases = getCases();
     for (CaseMap::value_type& entry :  testCases)
     {
         const string& name = entry.first;
         TestCasePtr pTest = entry.second;
         if (check(name))
         {
             stringVector values;
             values.reserve(labels.size());
             values.push_back(name);
             try
             {
                 auto start = std::chrono::high_resolution_clock::now();
                 {
                     //                  out << "Buildup Test: " << name << std::endl;
                     auto start = std::chrono::high_resolution_clock::now();
                     pTest->buildUp();
                     auto end = std::chrono::high_resolution_clock::now();
                     std::chrono::duration<double, std::milli> elapsed = end - start;
                     values.push_back(cast<string>(elapsed.count()));
                 }
                 {
                     //              out << "Run Test: " << name << std::endl;
                     auto start = std::chrono::high_resolution_clock::now();
                     switch (pTest->runTest())
                     {
                     case TestResult::Successful:
                         values.push_back("Succeed");
                         //out << "Test " << name << " successfully completed" << std::endl;
                         break;
                     case TestResult::Failed:
                         values.push_back("Failed");
                         //out << "Test " << name << " failed" << std::endl;
                         break;
                     default:
                         values.push_back("Error");
                         //out << "Test " << name << " failed with unexpected result" << std::endl;
                         break;
                     }
                     auto end = std::chrono::high_resolution_clock::now();
                     std::chrono::duration<double, std::milli> elapsed = end - start;
                     values.push_back(cast<string>(elapsed.count()));
                 }
                 {
                     //out << "Breakdown Test: " << name << std::endl;
                     auto start = std::chrono::high_resolution_clock::now();
                     pTest->breakDown();
                     auto end = std::chrono::high_resolution_clock::now();
                     std::chrono::duration<double, std::milli> elapsed = end - start;
                     values.push_back(cast<string>(elapsed.count()));
                 }
                 auto end = std::chrono::high_resolution_clock::now();
                 std::chrono::duration<double, std::milli> elapsed = end - start;
                 values.push_back(cast<string>(elapsed.count()));
                 outputs.push_back(values);
             }
             catch (std::exception& e)
             {
                 out << "Test " << name << " failed: " << e.what() << std::endl;
                 return TestResult::Exception;
             }
             catch (...)
             {
                 out << "Test " << name << " failed with unexpected exception" << std::endl;
                 return TestResult::Unexpected;
             }
         }
     }
     writeOutput(outputs);
     return TestResult::Successful;
 }
References anonymous_namespace{TestCase.cpp}::getCases(), out, and Successful.
Referenced by OnStartTestClicked().
writeOutput()
void TestCase::writeOutput (const VectorOfStringVectors & outputs) static
Definition at line 143 of file TestCase.cpp.
 {
     if (outputs.size() > 1) // if 1, no tests were performed
     {
         const stringVector& labels = outputs.front();
         vector<size_t> colLengts(labels.size(), 0);
         for (size_t col = 0; col < labels.size(); ++col)
         {
             for (const stringVector& values : outputs)
                 colLengts[col] = max(values[col].length(), colLengts[col]);
         }
         for (const stringVector& values : outputs)
         {
             for (size_t col = 0; col < labels.size(); ++col)
             {
                 const string label = labels.at(col);
                 if (values.size() > col)
                 {
                     string value = values.at(col);
                     value += string((colLengts[col] -  value.length()), ' ');
                     out << value << '\t';
                 }
                 else
                 {
                     string value(colLengts[col], ' ');
                     out << value << '\t';
                 }
             }
             out << endl;
         }
     }
 }
References out.
The documentation for this class was generated from the following files:
src/Test/TestCase.h
src/Test/TestCase.cpp