The Simpelst Windows App: Button Class Reference
Button Class Reference
#include <Button.h>
Classes
struct Impl
Public Member Functions
Button ()
virtual ~Button ()
HWND create (HWND hParent, int x, int y, int cx, int cy, string caption)
virtual bool execute (int command)
Public Member Functions inherited from Control
Control ()
virtual ~Control ()
virtual HWND create (HWND hParent, int x, int y, int cx, int cy, string windowClass, string caption, int windowStyle)
virtual void insert (HWND hWnd)
Public Attributes
PropertyRW< function< void(Button *)> > OnClicked
Public Attributes inherited from Control
PropertyRW< HWND > hWnd
PropertyRW< string > Caption
Static Public Attributes
static Control::ControlManagerImpl< Button > Manager
Static Public Attributes inherited from Control
static struct Control::ControlManager Manager
Private Attributes
unique_ptr< Impl > pImpl_
Additional Inherited Members
Protected Member Functions inherited from Control
virtual LRESULT wndProc (HWND hWnd, UINT message, WPARAM wParam, LPARAM lParam)
Detailed Description
Definition at line 8 of file Button.h.
Constructor & Destructor Documentation
Button()
Button::Button ()
Definition at line 16 of file Button.cpp.
 : pImpl_(make_unique<Button::Impl>())
 , OnClicked(pImpl_->onClicked_)
 {
 }
~Button()
Button::~Button () virtual
Definition at line 22 of file Button.cpp.
 {
 }
Member Function Documentation
create()
HWND Button::create (HWND hParent, int x, int y, int cx, int cy, string caption)
Definition at line 27 of file Button.cpp.
 {
     return Control::create(hParent,
                            x,
                            y,
                            cx,
                            cy,
                            "BUTTON",
                            caption,
                            WS_CHILD | WS_VISIBLE | BS_PUSHBUTTON
                            );
 }
References Control::create().
Referenced by WndProc().
execute()
bool Button::execute (int command) virtual
Reimplemented from Control.
Definition at line 40 of file Button.cpp.
 {
     switch (command)
     {
     case BN_CLICKED:
         OnClicked(this);
         return true;
     default:
         return false;
     }
 }
References OnClicked.
Member Data Documentation
Manager
Control::ControlManagerImpl< Button > Button::Manager static
Definition at line 14 of file Button.h.
Referenced by OnStartClicked(), and WndProc().
OnClicked
PropertyRW<function<void(Button*)> > Button::OnClicked
Definition at line 24 of file Button.h.
Referenced by execute(), and WndProc().
pImpl_
unique_ptr<Impl> Button::pImpl_ private
Definition at line 21 of file Button.h.
The documentation for this class was generated from the following files:
src/Controls/Button.h
src/Controls/Button.cpp