The Simpelst Windows App: TestRunner Class Reference
TestRunner Class Reference
#include <TestRunner.h>
Static Public Member Functions
static void StartTests (const string &pattern)
Detailed Description
Definition at line 4 of file TestRunner.h.
Member Function Documentation
StartTests()
void TestRunner::StartTests (const string & pattern) static
Definition at line 24 of file TestRunner.cpp.
 {
     EditPtr output = Edit::Manager["Output:Edit"];
     output->Caption = "";
     output->add(format("Start tests with filter '%s'\r\n", pattern.c_str()));
     TestCase::runTests(pattern);
 }
References format(), Edit::Manager, and TestCase::runTests().
Referenced by OnStartTestClicked().
The documentation for this class was generated from the following files:
src/Test/TestRunner.h
src/Test/TestRunner.cpp