The Simpelst Windows App: anonymous_namespace{ValueTests.cpp} Namespace Reference
anonymous_namespace{ValueTests.cpp} Namespace Reference
Functions
void stackTests ()
Tests all functionality on stacked Values.
void heapTests ()
Test the functionality if Values are on heap, encapsulated in shared_ptr.
Variables
bool test = TestCase::addTestCase(S(ValueTests), make_shared<ValueTests>())
Function Documentation
heapTests()
void anonymous_namespace ValueTests anonymous_namespace{ValueTests.cpp}::cpp::heapTests ()
Test the functionality if Values are on heap, encapsulated in shared_ptr.
Creation / Assignement
Copying / Instances
Definition at line 59 of file ValueTests.cpp.
     {
         ValuePtr bv1(false);
         ValuePtr    bv2 = bv1;
         AssertTrue( bv2.use_count() == 2, "");
         BooleanValuePtr ptr1 = bv1, ptr2 = bv2;
         AssertTrue((*ptr1 == *ptr2), "");
         AssertTrue( bv2.use_count() == 4, "");
         bv2 = true;
         BooleanValuePtr ptr3 = bv2;
         AssertFalse((*ptr1 == *ptr3), "");
         AssertTrue( bv2.use_count() == 2, "");
         AssertTrue( bv1.use_count() == 3, "");
     }
References AssertFalse, and AssertTrue.
Referenced by ValueTests::runTest().
stackTests()
void anonymous_namespace ValueTests anonymous_namespace{ValueTests.cpp}::cpp::stackTests ()
Tests all functionality on stacked Values.
Assignment
Copying
Serialize to string
Deserialze from string
Definition at line 36 of file ValueTests.cpp.
     {
         BooleanValue booleanValue1(false);
         booleanValue1 = true;
         string booeanString = booleanValue1.writeString();
         BooleanValue booleanValue2(false);
         booleanValue2.readString(booeanString);
         Int32Value intValue1 = 33;
         string intStr = intValue1.writeString();
         Int32Value intValue2 = -42;
         intValue2.readString(intStr);
     }
References ValueImpl< T >::readString(), and ValueImpl< T >::writeString().
Referenced by ValueTests::runTest().
Variable Documentation
test
bool anonymous_namespace{ValueTests.cpp}::test = TestCase::addTestCase(S(ValueTests), make_shared<ValueTests>())
Definition at line 6 of file ValueTests.cpp.