The Simpelst Windows App: src/output.hpp File Reference
output.hpp File Reference
#include <stdarg.h>
#include <string>
#include <sstream>
#include <vector>
#include "Edit.h"
Classes
class outputbuf< Elem >
class output_stream< Elem >
struct LogHelper
Macros
#define LOG LogHelper(LOG_SOURCE)
#define DETAILED_LOG(msg) LogHelper(LOG_SOURCE, msg)
Typedefs
using StringVector = vector< string >
using VectorOfStringVectors = vector< StringVector >
using OutputStream = output_stream< char >
Functions
string format (const char *fmt,...)
template<typename Elem >
void flush (std::basic_string< Elem > &msg)
template<>
void flush (std::basic_string< wchar_t > &msg)
Macro Definition Documentation
DETAILED_LOG
#define DETAILED_LOG (msg) LogHelper(LOG_SOURCE, msg)
Definition at line 154 of file output.hpp.
LOG
#define LOG LogHelper(LOG_SOURCE)
Definition at line 153 of file output.hpp.
Typedef Documentation
OutputStream
using OutputStream = output_stream<char>
Definition at line 114 of file output.hpp.
StringVector
using StringVector = vector<string>
Definition at line 16 of file output.hpp.
VectorOfStringVectors
using VectorOfStringVectors = vector<StringVector>
Definition at line 17 of file output.hpp.
Function Documentation
flush() [1/2]
template<typename Elem > void flush (std::basic_string< Elem > & msg) inline
Definition at line 36 of file output.hpp.
 {
     if (msg.empty())
         return;
     EditPtr output = Edit::Manager["Output:Edit"];
     output->add(msg.c_str());
     output->add("\r\n");
     if (::IsDebuggerPresent())
     {
         OutputDebugStringA(msg.c_str());
         OutputDebugStringA("\n");
     }
 }
References Edit::add(), and Edit::Manager.
Referenced by outputbuf< Elem >::flushMsg().
flush() [2/2]
template<> void flush (std::basic_string< wchar_t > & msg) inline
Definition at line 53 of file output.hpp.
 {
     if (msg.empty())
         return;
     if (::IsDebuggerPresent())
     {
         OutputDebugStringW(msg.c_str());
         OutputDebugStringW(L"\n");
     }
 }
format()
string format (const char * fmt, ...) inline
Definition at line 21 of file output.hpp.
 {
     va_list args;
     va_start(args, fmt);
     size_t len = _vscprintf(fmt, args) + (size_t)1; // _vscprintf doesn't count terminating '\0'
     char* buf = new char[len * sizeof(char)];
     _vsnprintf_s(buf, len, len, fmt, args);
     string msg_;
     msg_ = buf;
     delete[] buf;
     va_end(args);
     return msg_;
 }
Referenced by OnStartTestClicked(), and LogHelper::operator()().