The Simpelst Windows App: Thread::ThreadManager::Impl Struct Reference
Thread::ThreadManager::Impl Struct Reference
The implementation of the thread manager.
Public Member Functions
~Impl ()
>An helper construct to prevent the application from crashing on exit.
ThreadPtr getOrCreateThread (const string &name)
Returns the thread with the given name. If none exists yet, it is created now.
ThreadPtr getThread (const ThreadId &id) const
Returns the Thread object with the resulting ThreadId. If no such thread exists, an empty ThreadPtr is returned.
ThreadPtr getThread (const string &name) const
Returns the Thread object with the resulting ThreadId. If no such thread exists, an empty ThreadPtr is returned.
Public Attributes
recursive_mutex mutex_
map< ThreadId, weak_ptr< Thread > > idMap_
map< string, weak_ptr< Thread > > nameMap_
Static Public Attributes
static bool isDeleted = false
Detailed Description
The implementation of the thread manager.
Definition at line 408 of file Thread.cpp.
Constructor & Destructor Documentation
~Impl()
Thread::ThreadManager::Impl::~Impl () inline
>An helper construct to prevent the application from crashing on exit.
Definition at line 411 of file Thread.cpp.
     {
         // If the globally stored main thread is released on termination, the manager may already be cleared
         isDeleted = true;
         std::vector<weak_ptr<Thread>> threads;
         for (map<ThreadId, weak_ptr<Thread>>::value_type vt : idMap_)
             threads.push_back(vt.second);
         for ( weak_ptr<Thread> twp : threads)
         {
             ThreadPtr thread = twp.lock();
             if (thread)
                 thread->stop();
         }
         this_thread::yield();
         for ( weak_ptr<Thread> twp : threads)
         {
             ThreadPtr thread = twp.lock();
             if (thread && thread->joinable())
                 thread->join();
         }
     }
References Thread::join(), Thread::joinable(), and Thread::stop().
Member Function Documentation
getOrCreateThread()
ThreadPtr Thread::ThreadManager::Impl::getOrCreateThread (const string & name)
Returns the thread with the given name. If none exists yet, it is created now.
Parameters
name
Returns
ThreadPtr
Definition at line 445 of file Thread.cpp.
 {
     lock_guard<recursive_mutex> lock(mutex_);
     ThreadPtr threadPtr;
     auto res = nameMap_.insert(make_pair(name, threadPtr));
     if (res.second)
     {
         weak_ptr<Thread>& weakPtr = res.first->second;
         threadPtr = ThreadPtr(new Thread(name));
         weakPtr = threadPtr;
     }
     else
     {
         weak_ptr<Thread>& weakPtr = res.first->second;
         threadPtr = weakPtr.lock();
     }
     return threadPtr;
 }
getThread() [1/2]
ThreadPtr Thread::ThreadManager::Impl::getThread (const string & name) const
Returns the Thread object with the resulting ThreadId. If no such thread exists, an empty ThreadPtr is returned.
Parameters
name
Returns
ThreadPtr
Definition at line 482 of file Thread.cpp.
 {
     lock_guard<recursive_mutex> lock(mutex_);
     auto it = nameMap_.find(name);
     if (it != nameMap_.end())
     {
         const weak_ptr<Thread>& weakPtr = it->second;
         return weakPtr.lock();
     }
     return ThreadPtr();
 }
getThread() [2/2]
ThreadPtr Thread::ThreadManager::Impl::getThread (const ThreadId & id) const
Returns the Thread object with the resulting ThreadId. If no such thread exists, an empty ThreadPtr is returned.
Parameters
id
Returns
ThreadPtr
Definition at line 468 of file Thread.cpp.
 {
     lock_guard<recursive_mutex> lock(mutex_);
     auto it = idMap_.find(id);
     if (it != idMap_.end())
     {
         const weak_ptr<Thread>& thread = it->second;
         return thread.lock();
     }
     return ThreadPtr();
 }
Member Data Documentation
idMap_
map<ThreadId, weak_ptr<Thread> > Thread::ThreadManager::Impl::idMap_
Definition at line 434 of file Thread.cpp.
isDeleted
bool Thread::ThreadManager::Impl::isDeleted = false static
Definition at line 410 of file Thread.cpp.
Referenced by Thread::~Thread().
mutex_
recursive_mutex Thread::ThreadManager::Impl::mutex_ mutable
Definition at line 433 of file Thread.cpp.
nameMap_
map<string, weak_ptr<Thread> > Thread::ThreadManager::Impl::nameMap_
Definition at line 435 of file Thread.cpp.
The documentation for this struct was generated from the following file:
src/Base/Thread.cpp