The Simpelst Windows App: Thread::Impl Struct Reference
Thread::Impl Struct Reference
The real implementation of Thread.
Public Member Functions
Impl (const string &name)
void enqueue (function< void()> f)
A new function object is added to the waiting queue.
void notify ()
notify condition or notify-functor
void initRunningThread (ThreadId id, function< void()> notify, ThreadPtr pThread)
initialize a running thread.
void processQueue (unique_lock< recursive_mutex > &lock, size_t maxElements)
process the queue of functors, usually called form notify-functor
Static Public Member Functions
static void standardLoop (ThreadPtr pThread)
The normally used processing loop of a background thread.
Public Attributes
string name_
ThreadId id_
thread thread_
function< void()> notify_
recursive_mutex mutex_
condition_variable_any condition_
atomic_bool enqueued_ = false
atomic_bool stopped_ = false
queue< function< void()> > queue_
Detailed Description
The real implementation of Thread.
Hidden from the public eye, here effectively done
Definition at line 379 of file Thread.cpp.
Constructor & Destructor Documentation
Impl()
Thread::Impl::Impl (const string & name) inline
Definition at line 381 of file Thread.cpp.
     : name_(name)
     {}
Member Function Documentation
enqueue()
void Thread::Impl::enqueue (function< void()> f)
A new function object is added to the waiting queue.
Parameters
f
Definition at line 679 of file Thread.cpp.
 {
     {
         lock_guard<recursive_mutex> lock(mutex_);
         queue_.push(f);
         enqueued_ = true;
     }
     notify();
 }
initRunningThread()
void Thread::Impl::initRunningThread (ThreadId id, function< void()> notify, ThreadPtr pThread)
initialize a running thread.
Parameters
id
notify
pThread
Definition at line 664 of file Thread.cpp.
 {
     id_ = id;
     {
         lock_guard<recursive_mutex> lock(Thread::Manager.pImpl_->mutex_);
         Thread::Manager.pImpl_->nameMap_.insert(make_pair(name_, pThread));
     }
     notify_ = notify;
 }
References id_, Thread::Manager, name_, notify(), notify_, Thread::ThreadManager::pImpl_, and Thread::pImpl_.
notify()
void Thread::Impl::notify ()
notify condition or notify-functor
Definition at line 756 of file Thread.cpp.
 {
     if (notify_)
         notify_();
     else
         condition_.notify_one();
 }
Referenced by initRunningThread().
processQueue()
void Thread::Impl::processQueue (unique_lock< recursive_mutex > & lock, size_t maxElements)
process the queue of functors, usually called form notify-functor
Parameters
lock ///> The lock must set outside of this procedure
maxElements ///> If more elements in queue, notify is called
Definition at line 733 of file Thread.cpp.
 {
     for (size_t i = 0; i < maxElements && !queue_.empty(); ++i)
     {
         function<void()> f = queue_.front();
         queue_.pop();
 #pragma warning(push)
 #pragma warning(disable : 26110)
         lock.unlock();
 #pragma warning(pop)
         f();
         lock.lock();
         this_thread::yield();
     }
     if (!queue_.empty())
         notify();
 }
Referenced by standardLoop().
standardLoop()
void Thread::Impl::standardLoop (ThreadPtr pThread) static
The normally used processing loop of a background thread.
Parameters
pThread
Definition at line 694 of file Thread.cpp.
 {
     string threadName = pThread->Name;
     //std::wstring threadName = std::wstring_convert<std::codecvt_utf8<wchar_t>>().from_bytes(tn.c_str());
     //std::wstring threadName(tn.length(), L' ');// = std::wstring_convert<std::codecvt_utf8<wchar_t>>().from_bytes(tn.c_str());
     //std::copy(tn.begin(), tn.end(), threadName.begin());
     //HRESULT hr = SetThreadDescription(GetCurrentThread(), threadName.c_str());
     //assert(SUCCEEDED(hr));
     SetThreadName(::GetCurrentThreadId(), threadName.c_str());
     EditPtr output = Edit::Manager["Output:Edit"];
     output->add((ostringstream() << "start of thread " << threadName << "\r\n").str());
     Thread::Impl* pImpl = pThread->pImpl_.get();
     pImpl->condition_.notify_all();
     do
     {
         unique_lock<recursive_mutex> lock(pThread->pImpl_->mutex_);
         pImpl->condition_.wait(lock, [pImpl] { return pImpl->enqueued_.load() || pImpl->stopped_.load(); });
         pImpl->enqueued_ = false;
         pImpl->processQueue(lock, 10);
     } while (pImpl->stopped_ == false);
     {
         lock_guard<recursive_mutex> lock(Thread::Manager.pImpl_->mutex_);
         Thread::Manager.pImpl_->idMap_.erase(pImpl->id_);
     }
     pImpl->id_ = ThreadId();
     output->add((ostringstream() << "end of thread " << threadName << "\r\n").str());
 }
References Edit::add(), condition_, enqueued_, id_, Thread::Manager, Edit::Manager, Thread::Name, Thread::ThreadManager::pImpl_, Thread::pImpl_, processQueue(), SetThreadName(), and stopped_.
Referenced by Thread::start().
Member Data Documentation
condition_
condition_variable_any Thread::Impl::condition_
Definition at line 391 of file Thread.cpp.
Referenced by standardLoop().
enqueued_
atomic_bool Thread::Impl::enqueued_ = false
Definition at line 392 of file Thread.cpp.
Referenced by standardLoop().
id_
ThreadId Thread::Impl::id_
Definition at line 385 of file Thread.cpp.
Referenced by initRunningThread(), and standardLoop().
mutex_
recursive_mutex Thread::Impl::mutex_
Definition at line 390 of file Thread.cpp.
name_
string Thread::Impl::name_
Definition at line 384 of file Thread.cpp.
Referenced by initRunningThread().
notify_
function<void()> Thread::Impl::notify_
Definition at line 388 of file Thread.cpp.
Referenced by initRunningThread().
queue_
queue<function<void()> > Thread::Impl::queue_
Definition at line 393 of file Thread.cpp.
stopped_
atomic_bool Thread::Impl::stopped_ = false
Definition at line 392 of file Thread.cpp.
Referenced by standardLoop().
thread_
thread Thread::Impl::thread_
Definition at line 386 of file Thread.cpp.
The documentation for this struct was generated from the following file:
src/Base/Thread.cpp